server:
  port: 8081

spring:
  application:
    name: data4library

  ai:
    mcp:
      server:
        name: data4library
        version: 1.0.0
        protocol: sse

naru-api:
  api-key: ${NARU_API_KEY}
  base-url: http://data4library.kr/api