@baseUrl = http://data4library.kr/api
@authKey = 60bc1d7d1fde2a404cbb0fb74d4a4ce834b658001dd9a7583db32524cdaf5abf

### 도서나루 API 응답 확인
GET {{baseUrl}}/libSrch?authKey={{authKey}}&region=24&format=json

### searchBooks
GET {{baseUrl}}/srchBooks?authKey={{authKey}}&title=소년이 운다&format=json

### searchLibraries
GET {{baseUrl}}/libSrch?authKey={{authKey}}&region=11&format=json

### checkBookExists
GET {{baseUrl}}/bookExist?authKey={{authKey}}&libCode=711618&isbn13=9788958284178&format=json

### checkLoanAvailability
GET {{baseUrl}}/libSrchByBook?authKey={{authKey}}&isbn=9788958284178&region=11&format=json

### 도서 상세 정보 (srchDtlList) 또또또 옴
GET {{baseUrl}}/srchDtlList?authKey={{authKey}}&isbn13=9788960777330&loaninfoYN=Y&format=json

### 인기 대출 도서 (loanItemSrch) 옴
GET {{baseUrl}}/loanItemSrch?authKey={{authKey}}&startDt=2024-01-01&endDt=2024-12-31&region=29&format=json

### 대출 급상승 도서 (hotTrend) 옴
GET {{baseUrl}}/hotTrend?authKey={{authKey}}&searchDt=2024-01-01&format=json

### 추천 도서 - 마니아 (recommandList) 또옴
GET {{baseUrl}}/recommandList?authKey={{authKey}}&isbn13=9788960777330&type=mania&format=json

### 추천 도서 - 다독자 (recommandList) 또또옴
GET {{baseUrl}}/recommandList?authKey={{authKey}}&isbn13=9788960777330&type=reader&format=json